title: cocinalibre
email: cocinalibre.github.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  El lugar para disfrutar cocinando y comiendo...
permalink: #':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "davidebian/cocinalibre.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: cocinalibre # add your name
author-pic: logo.jpg
about-author: Amante de la vida, la cocina y el sotfware libre.

# Contact links
email: cocinalibre.github.io@gmail.com # Add your Email address
#phone: # Add your Phone number
#website: # Add your website, do not add http://
#linkedin: # Add your Linkedin handle
github: cocinalibre # Add your Github handle
twitter: '@davidebian' # Add your Twitter handle
#facebook: # Add your Facebook handle
#instagram: # Add your Instagram handle
#pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: cocinalibre-github-io # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

theme: jekyll-theme-cayman
